package org.datamancy.pipeline.core

import org.datamancy.pipeline.sinks.BookStackDocument


interface BookStackTransformable {
    fun toBookStackDocument(): BookStackDocument
}


object BookStackHtmlHelper {
    fun escapeHtml(text: String): String {
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;")
    }

    fun sanitizeForHtml(text: String): String {
        
        return escapeHtml(text)
    }

    fun formatMetadataBox(items: List<Pair<String, String>>): String {
        return """
            <div style="margin-bottom: 20px; padding: 15px; background-color: #f8f9fa; border-left: 4px solid #007bff;">
                ${items.joinToString("\n") { (label, value) ->
                    "<p><strong>$label:</strong> $value</p>"
                }}
            </div>
        """.trimIndent()
    }

    fun formatListSection(title: String, items: List<String>, maxItems: Int = 50): String {
        if (items.isEmpty()) return ""

        val displayItems = items.take(maxItems)
        val remaining = items.size - maxItems

        return """
            <div style="margin-top: 20px;">
                <h2>$title</h2>
                <ul>
                    ${displayItems.joinToString("\n") { "<li>$it</li>" }}
                    ${if (remaining > 0) "<li><em>... and $remaining more</em></li>" else ""}
                </ul>
            </div>
        """.trimIndent()
    }

    fun formatFooter(sourceDescription: String): String {
        return """
            <hr>
            <p style="font-size: 0.9em; color: #666;">
                <em>This page was automatically generated by Datamancy Pipeline from $sourceDescription</em>
            </p>
        """.trimIndent()
    }
}
