# SOPS configuration for Datamancy
# Automatically encrypts files matching patterns with Age

creation_rules:
  # Encrypt .env files with Age
  - path_regex: \.env(\..*)?$
    age: age1zlwf7ugfqawsamkuwymz33gawqm6r6rhu6k598w6dqya3jztkdjqzqh90p

  # Encrypt any files in secrets/ directory
  - path_regex: secrets/.*
    age: age1zlwf7ugfqawsamkuwymz33gawqm6r6rhu6k598w6dqya3jztkdjqzqh90p

  # Encrypt backup encryption keys
  - path_regex: .*backup.*\.key$
    age: age1zlwf7ugfqawsamkuwymz33gawqm6r6rhu6k598w6dqya3jztkdjqzqh90p