rootProject.name = "Datamancy"

// Include all Kotlin subprojects (standardized module IDs)
include(":model-context-server")
//include(":speech-gateway")
//include(":vllm-router")
//include(":stack-discovery")
//include(":playwright-controller")
//include(":ldap-sync-service")
//include(":vm-provisioner")
// NOTE: config-generator has been replaced by process-config-templates.main.kts
// Removed: include(":config-generator")

// Map subproject directories (standardized directories)
project(":model-context-server").projectDir = file("stack.kotlin/model-context-server")
//project(":speech-gateway").projectDir = file("stack.kotlin/speech-gateway")
//project(":vllm-router").projectDir = file("stack.kotlin/vllm-router")
//project(":stack-discovery").projectDir = file("stack.kotlin/stack-discovery")
//project(":playwright-controller").projectDir = file("stack.kotlin/playwright-controller")
//project(":ldap-sync-service").projectDir = file("stack.kotlin/ldap-sync-service")
//project(":vm-provisioner").projectDir = file("stack.kotlin/vm-provisioner")

// New services
//include(":task-scheduler")
include(":pipeline-common")
include(":knowledge-ingestion")
include(":embedding-worker")
include(":market-data-ingestion")
include(":market-data-sync")
include(":market-data-repair")
include(":market-data-persist")
include(":market-data-minute-staging")
include(":feature-materializer")
include(":market-data-state-updater")
include(":content-publisher")
include(":search-service")
//project(":task-scheduler").projectDir = file("stack.kotlin/task-scheduler")
project(":pipeline-common").projectDir = file("stack.kotlin/pipeline-common")
project(":knowledge-ingestion").projectDir = file("stack.kotlin/knowledge-ingestion")
project(":embedding-worker").projectDir = file("stack.kotlin/embedding-worker")
project(":market-data-ingestion").projectDir = file("stack.kotlin/market-data-ingestion")
project(":market-data-sync").projectDir = file("stack.kotlin/market-data-sync")
project(":market-data-repair").projectDir = file("stack.kotlin/market-data-repair")
project(":market-data-persist").projectDir = file("stack.kotlin/market-data-persist")
project(":market-data-minute-staging").projectDir = file("stack.kotlin/market-data-minute-staging")
project(":feature-materializer").projectDir = file("stack.kotlin/feature-materializer")
project(":market-data-state-updater").projectDir = file("stack.kotlin/market-data-state-updater")
project(":content-publisher").projectDir = file("stack.kotlin/content-publisher")
project(":search-service").projectDir = file("stack.kotlin/search-service")

include(":test-runner")
project(":test-runner").projectDir = file("tests.kotlin/test-runner")

// Trading system
include(":trading-sdk")
include(":tx-gateway")
include(":alpha-analytics-service")
project(":trading-sdk").projectDir = file("stack.kotlin/trading-sdk")
project(":tx-gateway").projectDir = file("stack.kotlin/tx-gateway")
project(":alpha-analytics-service").projectDir = file("stack.kotlin/alpha-analytics-service")

// Deprecated: stack-tests (replaced by test-runner)
// include(":stack-tests")
// project(":stack-tests").projectDir = file("src/stack-tests")
