rootProject.name = "Datamancy"

// Include all Kotlin subprojects (standardized module IDs)
include(":agent-tool-server")
//include(":speech-gateway")
//include(":vllm-router")
//include(":stack-discovery")
//include(":playwright-controller")
//include(":ldap-sync-service")
//include(":vm-provisioner")
// NOTE: config-generator has been replaced by process-config-templates.main.kts
// Removed: include(":config-generator")

// Map subproject directories (standardized directories)
project(":agent-tool-server").projectDir = file("src/agent-tool-server")
//project(":speech-gateway").projectDir = file("src/speech-gateway")
//project(":vllm-router").projectDir = file("src/vllm-router")
//project(":stack-discovery").projectDir = file("src/stack-discovery")
//project(":playwright-controller").projectDir = file("src/playwright-controller")
//project(":ldap-sync-service").projectDir = file("src/ldap-sync-service")
//project(":vm-provisioner").projectDir = file("src/vm-provisioner")

// New services
//include(":task-scheduler")
include(":data-fetcher")
include(":data-transformer")
include(":data-bookstack-writer")
include(":data-vector-indexer")
include(":search-service")
include(":control-panel")
//project(":task-scheduler").projectDir = file("src/task-scheduler")
project(":data-fetcher").projectDir = file("src/data-fetcher")
project(":data-transformer").projectDir = file("src/data-transformer")
project(":data-bookstack-writer").projectDir = file("src/data-bookstack-writer")
project(":data-vector-indexer").projectDir = file("src/data-vector-indexer")
project(":search-service").projectDir = file("src/search-service")
project(":control-panel").projectDir = file("src/control-panel")

// Test framework modules
include(":test-commons")
project(":test-commons").projectDir = file("src/test-commons")
include(":test-runner")
project(":test-runner").projectDir = file("src/test-runner")
// Deprecated: stack-tests (replaced by test-runner)
// include(":stack-tests")
// project(":stack-tests").projectDir = file("src/stack-tests")
