services:
  agent-tool-server:
    image: datamancy/agent-tool-server:local-build
    build:
      context: .
      dockerfile: ./containers.src/agent-tool-server/Dockerfile
    container_name: agent-tool-server
    restart: unless-stopped
    networks:
      ai:
        aliases:
          - agent-tool-server.${DOMAIN}
      postgres:
        aliases:
          - agent-tool-server.${DOMAIN}
      mariadb:
        aliases:
          - agent-tool-server.${DOMAIN}
      qdrant:
        aliases:
          - agent-tool-server.${DOMAIN}
      ldap:
        aliases:
          - agent-tool-server.${DOMAIN}
      docker-proxy:
        aliases:
          - agent-tool-server.${DOMAIN}
    depends_on:
      litellm:
        condition: service_started
      mariadb:
        condition: service_started
      postgres:
        condition: service_started
      postgres-observer-views:
        condition: service_completed_successfully
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_BASE_URL: http://litellm:4000
      POSTGRES_OBSERVER_USER: agent_observer
      POSTGRES_OBSERVER_PASSWORD: ${POSTGRES_AGENT_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MARIADB_OBSERVER_USER: agent_observer
      MARIADB_OBSERVER_PASSWORD: ${MARIADB_AGENT_PASSWORD}
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      QDRANT_OBSERVER_API_KEY: ${QDRANT_AGENT_API_KEY}
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6334
      LDAP_OBSERVER_DN: cn=agent_observer,${LDAP_BASE_DN}
      LDAP_OBSERVER_PASSWORD: ${LDAP_AGENT_PASSWORD}
      LDAP_HOST: ldap
      LDAP_PORT: 389
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      SEARCH_SERVICE_URL: http://search-service:8098
      MCP_GRANT_HOST_NETWORK_HTTP: "true"
      MCP_GRANT_HOST_NETWORK_SSH: "true"
      TOOLSERVER_SSH_HOST: ${STACK_SSH_HOST:-latium.local}
      TOOLSERVER_SSH_USER: ${STACK_SSH_USER:-stackops}
      TOOLSERVER_SSH_KEY_PATH: /app/known_hosts_data/keys/stackops_ed25519
      TOOLSERVER_SSH_KNOWN_HOSTS: /app/known_hosts_data/known_hosts
      TOOLSERVER_TOOL_EXEC_TIMEOUT_MS: 300000
      TOOLSERVER_ALLOW_CAPS: "host.network.http,host.network.ssh,host.shell.read,host.docker.inspect,host.docker.write,docker.container.create,docker.container.manage,ssh.keymanagement"
    volumes:
      - agent_tool_server_known_hosts:/app/known_hosts_data:ro
      - agent_tool_server_scripts:/app/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock.host:rw
    group_add:
      - "988"
    healthcheck:
      test:
        - CMD-SHELL
        - |
          wget --quiet --tries=1 --timeout=3 --spider http://localhost:8081/tools && \
          wget --quiet --tries=1 --timeout=3 -O- http://localhost:8081/tools | grep -q tools
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
