services:
  authelia:
    image: authelia/authelia:4.39.15
    container_name: authelia
    restart: unless-stopped
    networks:
      authelia:
        aliases:
          - auth.${DOMAIN}
      caddy:
        aliases:
          - auth.${DOMAIN}
      ldap:
        aliases:
          - auth.${DOMAIN}
      postgres:
        aliases:
          - auth.${DOMAIN}
      valkey:
        aliases:
          - auth.${DOMAIN}
    depends_on:
      ldap:
        condition: service_healthy
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
    environment:
      TZ: UTC
      DOMAIN: ${DOMAIN}
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
      AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
      AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ${AUTHELIA_OIDC_HMAC_SECRET}
      AUTHELIA_STORAGE_POSTGRES_PASSWORD: ${AUTHELIA_DB_PASSWORD}
      PGADMIN_OAUTH_SECRET: ${PGADMIN_OAUTH_SECRET}
      OPENWEBUI_OAUTH_SECRET: ${OPENWEBUI_OAUTH_SECRET}
      DIM_OAUTH_SECRET: ${DIM_OAUTH_SECRET}
      PLANKA_OAUTH_SECRET: ${PLANKA_OAUTH_SECRET}
      VAULTWARDEN_OAUTH_SECRET: ${VAULTWARDEN_OAUTH_SECRET}
      MASTODON_OIDC_SECRET: ${MASTODON_OIDC_SECRET}
      BOOKSTACK_OAUTH_SECRET: ${BOOKSTACK_OAUTH_SECRET}
      FORGEJO_OAUTH_SECRET: ${FORGEJO_OAUTH_SECRET}
      MATRIX_OAUTH_SECRET: ${MATRIX_OAUTH_SECRET}
    volumes:
      - authelia_data:/config
      - ./configs/authelia/configuration.yml:/config/configuration.yml:ro
      - ./configs/authelia/oidc_rsa.pem:/config/oidc_rsa.pem:ro
      - ./configs/authelia/entrypoint.sh:/entrypoint.sh:ro
    command:
      - --config
      - /config/configuration.yml
    entrypoint:
      - /entrypoint.sh
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9091/api/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 120s
