services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    container_name: autoheal
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      AUTOHEAL_CONTAINER_LABEL: "autoheal"
      AUTOHEAL_INTERVAL: 30
      AUTOHEAL_START_PERIOD: 0
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 10
      WEBHOOK_URL: "http://ntfy:80/datamancy-autoheal"
