services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:version-v24.12.1
    container_name: bookstack
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - bookstack.${DOMAIN}
      mariadb:
        aliases:
          - bookstack.${DOMAIN}
    depends_on:
      mariadb:
        condition: service_healthy
      mariadb-init:
        condition: service_completed_successfully
    environment:
      PUID: ${DOCKER_USER_ID:-1000}
      PGID: ${DOCKER_GROUP_ID:-1000}
      TZ: UTC
      APP_URL: https://bookstack.${DOMAIN}
      APP_KEY: ${BOOKSTACK_APP_KEY}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: bookstack
      DB_PASSWORD: ${BOOKSTACK_DB_PASSWORD}
      DB_DATABASE: bookstack
      BOOKSTACK_API_TOKEN_ID: ${BOOKSTACK_API_TOKEN_ID}
      BOOKSTACK_API_TOKEN_SECRET: ${BOOKSTACK_API_TOKEN_SECRET}
    volumes:
      - bookstack_data:/config
      - ./configs/bookstack/init:/custom-cont-init.d:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/login"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 300s
