services:
  caddy:
    image: caddy:2.10.2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      caddy:
        aliases:
          - www.${DOMAIN}
          - grafana.${DOMAIN}
          - open-webui.${DOMAIN}
          - vaultwarden.${DOMAIN}
          - app.vaultwarden.${DOMAIN}
          - planka.${DOMAIN}
          - bookstack.${DOMAIN}
          - jupyterhub.${DOMAIN}
          - homepage.${DOMAIN}
          - seafile.${DOMAIN}
          - api.seafile.${DOMAIN}
          - onlyoffice.${DOMAIN}
          - matrix.${DOMAIN}
          - api.matrix.${DOMAIN}
          - element.${DOMAIN}
          - homeassistant.${DOMAIN}
          - api.homeassistant.${DOMAIN}
          - litellm.${DOMAIN}
          - api.litellm.${DOMAIN}
          - auth.${DOMAIN}
          - kopia.${DOMAIN}
          - mail.${DOMAIN}
          - agent-tool-server.${DOMAIN}
          - lam.${DOMAIN}
          - forgejo.${DOMAIN}
          - qbittorrent.${DOMAIN}
      authelia:
      postgres:
      mariadb:
      qdrant:
      ldap:
      litellm:
      ai:
        aliases:
          - ${DOMAIN}
          - www.${DOMAIN}
          - auth.${DOMAIN}
          - grafana.${DOMAIN}
          - jupyterhub.${DOMAIN}
          - open-webui.${DOMAIN}
          - vaultwarden.${DOMAIN}
          - prometheus.${DOMAIN}
          - homepage.${DOMAIN}
          - ntfy.${DOMAIN}
          - qbittorrent.${DOMAIN}
          - mastodon.${DOMAIN}
          - forgejo.${DOMAIN}
          - bookstack.${DOMAIN}
          - planka.${DOMAIN}
          - kopia.${DOMAIN}
          - radicale.${DOMAIN}
          - homeassistant.${DOMAIN}
          - lam.${DOMAIN}
          - mail.${DOMAIN}
          - vault.${DOMAIN}
          - element.${DOMAIN}
          - search.${DOMAIN}
          - litellm.${DOMAIN}
      mailserver:
      memcached:
      matrix-internal:
      mastodon-internal:
      monitoring:
    environment:
      DOMAIN: ${DOMAIN}
      STACK_ADMIN_EMAIL: ${STACK_ADMIN_EMAIL}
      API_LITELLM_ALLOWLIST: ${API_LITELLM_ALLOWLIST}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./configs/caddy/certs:/certs
      - ./configs/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./configs/vaultwarden/index.html:/srv/vaultwarden/index.html:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        rm -f /data/caddy/locks/*.lock 2>/dev/null || true
        exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    healthcheck:
      test:
        - CMD-SHELL
        - |
          wget --quiet --tries=1 --spider --timeout=2 http://127.0.0.1:2019/config/ && \
          wget --quiet --tries=1 --spider --timeout=2 http://127.0.0.1:2019/reverse_proxy/upstreams && \
          caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile 2>&1 | grep -q "Valid configuration"
      interval: 5s
      timeout: 4s
      retries: 3
      start_period: 15s
