# ============================================================================
# Docker Socket Proxy - Secure Access to Isolated Docker VM
# ============================================================================
#
# Purpose: Provides secure, permission-controlled access to a Docker daemon
# running on an isolated VM (e.g., a separate physical machine for CI/CD,
# container builds, or security-sensitive workloads).
#
# Architecture:
#   1. isolated-docker-vm-tunnel: Establishes SSH tunnel to remote Docker host
#      - Connects via SSH to ISOLATED_DOCKER_VM_HOST (e.g., gerald@192.168.0.61)
#      - Forwards remote /var/run/docker.sock to local volume
#      - Requires SSH key authentication (mounts ~/.ssh)
#
#   2. docker-proxy: HAProxy-based security layer
#      - Provides fine-grained permission control (CONTAINERS, IMAGES, etc.)
#      - Exposes filtered Docker API on tcp://docker-proxy:2375
#      - Prevents dangerous operations (BUILD=0, EXEC=0, COMMIT=0)
#
# Usage:
#   - Set ISOLATED_DOCKER_VM_HOST to your remote Docker host (user@hostname)
#   - Ensure SSH key-based auth is configured (~/.ssh/id_rsa or similar)
#   - Other services connect via: DOCKER_HOST=tcp://docker-proxy:2375
#
# Example: Forgejo Runner
#   environment:
#     DOCKER_HOST: tcp://docker-proxy:2375
#
# Security Notes:
#   - Only enable required permissions (see environment variables below)
#   - Never expose docker-proxy ports to untrusted networks
#   - Use SSH key authentication only (no passwords)
# ============================================================================

services:
  isolated-docker-vm-tunnel:
    build:
      context: ${DATAMANCY_PROJECT_ROOT}/containers.src/isolated-docker-vm-tunnel
      dockerfile: Dockerfile
    image: datamancy/isolated-docker-vm-tunnel:latest
    container_name: isolated-docker-vm-tunnel
    restart: unless-stopped
    hostname: labware
    networks:
      - docker-proxy
      - caddy
    environment:
      ISOLATED_DOCKER_VM_HOST: ${ISOLATED_DOCKER_VM_HOST:-gerald@192.168.0.61}
    volumes:
      - ${HOME}/.ssh:/root/.ssh:ro
      - isolated-docker-vm-socket:/var/run
    healthcheck:
      test: ["CMD", "test", "-S", "/var/run/docker.sock"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  docker-proxy:
    image: tecnativa/docker-socket-proxy:v0.4.2
    container_name: docker-proxy
    restart: unless-stopped
    networks:
      - docker-proxy
    depends_on:
      isolated-docker-vm-tunnel:
        condition: service_healthy
    environment:
      # Explicitly set socket path for HAProxy backend configuration
      SOCKET_PATH: /var/run/docker.sock

      # Permissions - only enable what's needed
      CONTAINERS: 1    # List/inspect containers
      IMAGES: 1        # List/inspect images
      NETWORKS: 1      # List/inspect networks
      VOLUMES: 1       # List/inspect volumes
      POST: 1          # Allow POST requests (create/start/stop)
      DELETE: 1        # Allow DELETE requests (remove containers/images)
      INFO: 1          # Docker daemon info
      VERSION: 1       # Docker version

      # Additional operations
      BUILD: 1         # Enable docker build for CI/CD
      COMMIT: 0        # Disable container commits
      EXEC: 1          # Enable container exec for tests/diagnostics
    volumes:
      - type: volume
        source: isolated-docker-vm-socket
        target: /var/run
        read_only: false
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:2375/version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  isolated-docker-vm-socket:
