services:
  docker-health-exporter:
    image: fviolence/docker-health-exporter:latest
    container_name: docker-health-exporter
    restart: unless-stopped
    networks:
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:9066/metrics', timeout=30)"]
      interval: 60s
      timeout: 35s
      retries: 5
      start_period: 120s
