services:
  dozzle:
    image: amir20/dozzle:v8.10.1
    container_name: dozzle
    restart: unless-stopped
    networks:
      - caddy
      - authelia
      - monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DOZZLE_BASE: /dozzle
      DOZZLE_LEVEL: info
      DOZZLE_FILTER: "status=running"
      DOZZLE_NO_ANALYTICS: "true"
      DOZZLE_ENABLE_ACTIONS: "false"
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
