services:
  evm-broadcaster:
    image: datamancy/evm-broadcaster:local-build
    build:
      context: ./containers.src/evm-broadcaster
      dockerfile: Dockerfile
    container_name: evm-broadcaster
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - trading
      - postgres
    depends_on:
      postgres:
        condition: service_started
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: txgateway
      POSTGRES_USER: txgateway
      POSTGRES_PASSWORD: ${POSTGRES_TXGATEWAY_PASSWORD}
      BASE_RPC_URL: ${BASE_RPC_URL:-https://mainnet.base.org}
      ARBITRUM_RPC_URL: ${ARBITRUM_RPC_URL:-https://arb1.arbitrum.io/rpc}
      OPTIMISM_RPC_URL: ${OPTIMISM_RPC_URL:-https://mainnet.optimism.io}
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8081/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
