services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:9.0
    container_name: forgejo
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - forgejo.${DOMAIN}
      postgres:
        aliases:
          - forgejo.${DOMAIN}
      internet:
    depends_on:
      postgres:
        condition: service_started
    environment:
      USER_UID: ${DOCKER_USER_ID:-1000}
      USER_GID: ${DOCKER_GROUP_ID:-1000}
      FORGEJO__database__DB_TYPE: postgres
      FORGEJO__database__HOST: postgres:5432
      FORGEJO__database__NAME: forgejo
      FORGEJO__database__USER: forgejo
      FORGEJO__database__PASSWD: ${POSTGRES_FORGEJO_PASSWORD}
      FORGEJO__server__DOMAIN: forgejo.${DOMAIN}
      FORGEJO__server__SSH_DOMAIN: forgejo.${DOMAIN}
      FORGEJO__server__ROOT_URL: https://forgejo.${DOMAIN}/
      FORGEJO__security__INSTALL_LOCK: true
      FORGEJO__service__DISABLE_REGISTRATION: true
      FORGEJO__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: true
      FORGEJO__service__REQUIRE_SIGNIN_VIEW: true
      FORGEJO__oauth2_client__ENABLE_AUTO_REGISTRATION: true
      FORGEJO__openid__ENABLE_OPENID_SIGNIN: true
      FORGEJO__openid__ENABLE_OPENID_SIGNUP: true
      FORGEJO__actions__ENABLED: true
      FORGEJO__actions__DEFAULT_ACTIONS_URL: https://code.forgejo.org
      FORGEJO_OAUTH_SECRET: ${FORGEJO_OAUTH_SECRET}
      DOMAIN: ${DOMAIN}
      STACK_ADMIN_PASSWORD: ${STACK_ADMIN_PASSWORD}
      STACK_ADMIN_EMAIL: ${STACK_ADMIN_EMAIL}
    volumes:
      - forgejo_data:/data
      - forgejo_runner_token:/runner-token
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./configs/forgejo/custom-entrypoint.sh:/custom-entrypoint.sh:ro
      - ./configs/forgejo/generate-runner-token.sh:/generate-runner-token.sh:ro
      - ./repos:/data/git/repositories:ro
    entrypoint: ["/custom-entrypoint.sh"]
    healthcheck:
      test:
        - CMD-SHELL
        - |
          wget --quiet --tries=1 --timeout=3 --spider http://localhost:3000/api/healthz && \
          wget --quiet --tries=1 --timeout=3 -O- http://localhost:3000/api/healthz | grep -q '{}'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
