services:
  jupyterhub:
    image: datamancy-jupyterhub:5.4.3
    build:
      context: ./containers.src/jupyterhub
      dockerfile: Dockerfile
    container_name: jupyterhub
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - jupyterhub.${DOMAIN}
      litellm:
        aliases:
          - jupyterhub.${DOMAIN}
      docker-proxy:
        aliases:
          - jupyterhub.${DOMAIN}
    depends_on:
      valkey:
        condition: service_started
    environment:
      DOCKER_NETWORK_NAME: datamancy-stack_litellm
      LITELLM_API_KEY: ${LITELLM_MASTER_KEY}
      JUPYTERHUB_CRYPT_KEY: ${JUPYTERHUB_CRYPT_KEY}
    volumes:
      - jupyterhub_data:/srv/jupyterhub
      - ./configs/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/hub/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
