services:
  kopia:
    image: kopia/kopia:0.22.3
    container_name: kopia
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - kopia.${DOMAIN}
      internet:
    environment:
      KOPIA_PASSWORD: ${STACK_ADMIN_PASSWORD}
      KOPIA_REPO_PATH: /app/repository
      USER: kopia
    volumes:
      - kopia_data:/app
      - postgres_data:/backup/postgres:ro
      - mariadb_data:/backup/mariadb:ro
      - ./configs/kopia/init-kopia.sh:/init-kopia.sh:ro
    entrypoint:
      - sh
      - /init-kopia.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:51515/ || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
