services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    restart: unless-stopped
    networks:
      - ldap
    environment:
      LDAP_ORGANISATION: Datamancy
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      LDAP_TLS: false
      LDAP_MEMBEROF_OVERLAY: true
      LDAP_MEMBEROF_GROUP_OC: groupOfNames
      LDAP_MEMBEROF_MEMBER_AD: member
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./configs/ldap/bootstrap_ldap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap_ldap.ldif:ro
    command: --copy-service --loglevel info
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -x -H ldap://localhost:389 -b '' -s base '(objectclass=*)' namingContexts >/dev/null 2>&1"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 180s
