services:
  mariadb:
    image: mariadb:11.8.5
    container_name: mariadb
    restart: unless-stopped
    networks:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ADMIN_PASSWORD}
      MYSQL_DATABASE: datamancy
      MARIADB_BOOKSTACK_PASSWORD: ${MARIADB_BOOKSTACK_PASSWORD}
      MARIADB_SEAFILE_PASSWORD: ${MARIADB_SEAFILE_PASSWORD}
      MARIADB_AGENT_PASSWORD: ${MARIADB_AGENT_PASSWORD}
    volumes:
      - ${NOCOW_DB_DIR}/mariadb:/var/lib/mysql
      - ./configs/mariadb/init-template.sql:/docker-entrypoint-initdb.d/init-template.sql:ro
      - ./configs/mariadb/init-wrapper.sh:/docker-entrypoint-initdb.d/01-init-wrapper.sh:ro
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test:
        - CMD-SHELL
        - |
          healthcheck.sh --connect --innodb_initialized && \
          mariadb -u root -p"$$MYSQL_ROOT_PASSWORD" -e "SELECT 1" >/dev/null
      interval: 60s
      timeout: 10s
      retries: 20
      start_period: 60s

