services:
  onlyoffice:
    image: onlyoffice/documentserver:8.3.3
    container_name: onlyoffice
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - onlyoffice.${DOMAIN}
    environment:
      JWT_ENABLED: true
      JWT_SECRET: ${ONLYOFFICE_JWT_SECRET}
    volumes:
      - onlyoffice_data:/var/www/onlyoffice
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/healthcheck"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
