services:
  pipeline:
    image: datamancy/pipeline:local-build
    build:
      context: .
      dockerfile: ./containers.src/pipeline/Dockerfile
    container_name: pipeline
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    profiles:
      - ingestion
    networks:
      - qdrant
      - postgres
      - ai
      - internet
      - mariadb
    depends_on:
      qdrant:
        condition: service_started
      postgres:
        condition: service_started
      embedding-service:
        condition: service_started
      bookstack:
        condition: service_started
    environment:
      RSS_SCHEDULE_MINUTES: "60"
      RSS_FEED_URLS: "https://hnrss.org/frontpage,https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml,https://www.reddit.com/r/programming/.rss,https://feeds.arstechnica.com/arstechnica/index"

      CVE_API_KEY: "${CVE_API_KEY:-}"
      CVE_SCHEDULE_MINUTES: "1440"
      CVE_MAX_RESULTS: "2147483647"

      TORRENTS_DATA_PATH: "https://codeberg.org/heretic/torrents-csv-data/raw/branch/main/torrents.csv"
      TORRENTS_SCHEDULE_MINUTES: "10080"
      TORRENTS_MAX_RESULTS: "2147483647"

      WIKIPEDIA_DUMP_PATH: "https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2"
      WIKIPEDIA_SCHEDULE_MINUTES: "43200"
      WIKIPEDIA_MAX_ARTICLES: "2147483647"

      AUSTRALIAN_LAWS_JURISDICTIONS: "commonwealth,nsw,vic,qld,wa,sa,tas,act,nt"
      AUSTRALIAN_LAWS_MAX_PER_JURISDICTION: "100"
      AUSTRALIAN_LAWS_START_YEAR: "2020"
      AUSTRALIAN_LAWS_SCHEDULE_MINUTES: "1440"

      LINUX_DOCS_SOURCES: "MAN_PAGES,DEBIAN_DOCS"
      LINUX_DOCS_SCHEDULE_MINUTES: "10080"
      LINUX_DOCS_MAX: "2147483647"

      WIKI_TYPES: "DEBIAN,ARCH"
      WIKI_MAX_PAGES_PER_WIKI: "500"
      WIKI_SCHEDULE_MINUTES: "10080"

      EMBEDDING_SERVICE_URL: http://embedding-service:8080
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6334
      QDRANT_API_KEY: ${QDRANT_ADMIN_API_KEY}
      POSTGRES_JDBC_URL: jdbc:postgresql://postgres:5432/datamancy
      POSTGRES_USER: ${POSTGRES_PIPELINE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PIPELINE_PASSWORD}

      BOOKSTACK_ENABLED: "true"
      BOOKSTACK_URL: "http://bookstack:80"
      BOOKSTACK_TOKEN_ID: ${BOOKSTACK_API_TOKEN_ID}
      BOOKSTACK_TOKEN_SECRET: ${BOOKSTACK_API_TOKEN_SECRET}

      QDRANT_RSS_COLLECTION: rss_feeds
      QDRANT_CVE_COLLECTION: cve
      QDRANT_TORRENTS_COLLECTION: torrents
      QDRANT_MARKET_COLLECTION: market_data
      QDRANT_WIKIPEDIA_COLLECTION: wikipedia
      QDRANT_AUSTRALIAN_LAWS_COLLECTION: australian_laws
      QDRANT_LINUX_DOCS_COLLECTION: linux_docs
      QDRANT_DEBIAN_WIKI_COLLECTION: debian_wiki
      QDRANT_ARCH_WIKI_COLLECTION: arch_wiki
    volumes:
      - pipeline_data:/data
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 wget --quiet --tries=1 -O /dev/null http://127.0.0.1:8090/health || exit 1"]
      interval: 60s
      timeout: 20s
      retries: 3
      start_period: 60s
