services:
  planka:
    image: ghcr.io/plankanban/planka:1.26.3
    container_name: planka
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - planka.${DOMAIN}
      postgres:
        aliases:
          - planka.${DOMAIN}
      authelia:
        aliases:
          - planka.${DOMAIN}
    depends_on:
      postgres:
        condition: service_healthy
      authelia:
        condition: service_started
    environment:
      BASE_URL: https://planka.${DOMAIN}
      DATABASE_URL: postgresql://planka:${POSTGRES_PLANKA_PASSWORD_ENCODED:-${POSTGRES_PLANKA_PASSWORD}}@postgres:5432/planka
      SECRET_KEY: ${PLANKA_SECRET_KEY}
      OIDC_ISSUER: https://auth.${DOMAIN}
      OIDC_CLIENT_ID: planka
      OIDC_CLIENT_SECRET: ${PLANKA_OAUTH_SECRET}
      OIDC_SCOPES: openid profile email groups
      OIDC_ADMIN_ROLES: admins
      OIDC_EMAIL_ATTRIBUTE: email
      OIDC_NAME_ATTRIBUTE: name
      OIDC_USERNAME_ATTRIBUTE: preferred_username
      OIDC_REDIRECT_URI: https://planka.${DOMAIN}/oidc-callback
      OIDC_AUTHORIZATION_ENDPOINT: https://auth.${DOMAIN}/api/oidc/authorization
      OIDC_TOKEN_ENDPOINT: https://auth.${DOMAIN}/api/oidc/token
      OIDC_USERINFO_ENDPOINT: https://auth.${DOMAIN}/api/oidc/userinfo
      OIDC_TOKEN_ENDPOINT_AUTH_METHOD: client_secret_post
      OIDC_ENFORCED: false
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/caddy-ca.crt
    volumes:
      - planka_data:/app/public/user-avatars
      - planka_caddy_ca:/usr/local/share/ca-certificates:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:1337/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
