services:
  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    restart: unless-stopped
    networks:
      - caddy
    environment:
      TZ: UTC
    volumes:
      - radicale_data:/data
      - ./configs/radicale/config:/etc/radicale/config:ro
      - ./configs/radicale/users:/data/users
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5232/.web/"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
