services:
  registry:
    image: registry:2.8
    container_name: registry
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - registry.${DOMAIN}
      docker-proxy:
        aliases:
          - registry.${DOMAIN}
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: ""
      REGISTRY_HTTP_TLS_KEY: ""
      REGISTRY_VALIDATION_DISABLED: "true"
    volumes:
      - registry_data:/var/lib/registry
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
