services:
  roundcube-init:
    image: postgres:16.11
    container_name: roundcube-init
    restart: "no"
    networks:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_ROUNDCUBE_PASSWORD: ${POSTGRES_ROUNDCUBE_PASSWORD}
    volumes:
      - ./configs/postgres/roundcube-schema.sql:/tmp/roundcube-schema.sql:ro
    command:
      - bash
      - -c
      - |
        echo "Initializing Roundcube database schema..."

        until pg_isready -h postgres -U ${POSTGRES_ADMIN_USER}; do
          echo "Waiting for postgres..."
          sleep 2
        done

        TABLE_EXISTS=$$(PGPASSWORD="$$PGPASSWORD" psql -h postgres -U "$$POSTGRES_USER" -d roundcube -tAc "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'session');")

        if [ "$$TABLE_EXISTS" = "t" ]; then
          echo "Roundcube schema already initialized, skipping..."
          exit 0
        fi

        echo "Applying Roundcube schema from bundled file..."
        PGPASSWORD="$$PGPASSWORD" psql -h postgres -U "$$POSTGRES_USER" -d roundcube -f /tmp/roundcube-schema.sql

        echo "Granting permissions to roundcube user..."
        PGPASSWORD="$$PGPASSWORD" psql -h postgres -U "$$POSTGRES_USER" -d roundcube <<-EOSQL
          GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO roundcube;
          GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO roundcube;
        EOSQL

        echo "Roundcube database schema initialized successfully!"

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    networks:
      - caddy
      - mailserver
      - postgres
    depends_on:
      mailserver:
        condition: service_started
      postgres:
        condition: service_started
      roundcube-init:
        condition: service_completed_successfully
    environment:
      ROUNDCUBEMAIL_DB_TYPE: pgsql
      ROUNDCUBEMAIL_DB_HOST: postgres
      ROUNDCUBEMAIL_DB_PORT: 5432
      ROUNDCUBEMAIL_DB_USER: roundcube
      ROUNDCUBEMAIL_DB_PASSWORD: ${POSTGRES_ROUNDCUBE_PASSWORD}
      ROUNDCUBEMAIL_DB_NAME: roundcube
      ROUNDCUBEMAIL_DEFAULT_HOST: mailserver
      ROUNDCUBEMAIL_DEFAULT_PORT: 143
      ROUNDCUBEMAIL_SMTP_SERVER: mailserver
      ROUNDCUBEMAIL_SMTP_PORT: 587
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 50M
    volumes:
      - roundcube_data:/var/www/html
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
