services:
  seafile:
    image: seafileltd/seafile-mc:13.0.15
    container_name: seafile
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - seafile.${DOMAIN}
          - api.seafile.${DOMAIN}
      mariadb:
        aliases:
          - seafile.${DOMAIN}
          - api.seafile.${DOMAIN}
      memcached:
        aliases:
          - seafile.${DOMAIN}
          - api.seafile.${DOMAIN}
    depends_on:
      volume-init:
        condition: service_completed_successfully
      mariadb:
        condition: service_healthy
      seafile-memcached:
        condition: service_started
    environment:
      TZ: UTC
      DB_HOST: mariadb
      DB_ROOT_PASSWD: ${MARIADB_ADMIN_PASSWORD}
      SEAFILE_MYSQL_DB_HOST: mariadb
      SEAFILE_MYSQL_DB_PORT: 3306
      SEAFILE_MYSQL_DB_USER: seafile
      SEAFILE_MYSQL_DB_PASSWORD: ${MARIADB_SEAFILE_PASSWORD}
      INIT_SEAFILE_MYSQL_ROOT_PASSWORD: ${MARIADB_ADMIN_PASSWORD}
      SEAFILE_SERVER_HOSTNAME: seafile.${DOMAIN}
      SEAFILE_ADMIN_EMAIL: ${STACK_ADMIN_EMAIL}
      SEAFILE_ADMIN_PASSWORD: ${STACK_ADMIN_PASSWORD}
      JWT_PRIVATE_KEY: ${SEAFILE_JWT_KEY}
      TIME_ZONE: UTC
      # Note: Redis cache removed due to authentication issues with seafile-mc image
      # Using default in-memory cache instead
      # CACHE_PROVIDER: redis
      # REDIS_HOST: valkey
      # REDIS_PORT: 6379
      # REDIS_USER: seafile
      # REDIS_PASSWORD: ${VALKEY_SEAFILE_PASSWORD}
    volumes:
      - seafile_files:/shared
      - seafile_media:/shared/seafile/library-template
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 360s  # Increased: Seafile needs time for MariaDB + Valkey initialization
