services:
  synapse-init:
    image: alpine:latest
    container_name: synapse-init
    restart: no
    networks:
      - postgres
    volumes:
      - synapse_data:/data
      - ./configs/synapse/entrypoint.sh:/tmp/entrypoint.sh:ro
    command:
      - sh
      - -c
      - |
        echo "Copying entrypoint and fixing Synapse volume ownership..."
        cp /tmp/entrypoint.sh /data/entrypoint.sh
        chmod +x /data/entrypoint.sh
        chown -R 991:991 /data
        echo "Synapse volume permissions fixed (UID:GID = 991:991)"


  synapse:
    image: matrixdotorg/synapse:v1.144.0
    container_name: synapse
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - matrix.${DOMAIN}
          - api.matrix.${DOMAIN}
      postgres:
        aliases:
          - matrix.${DOMAIN}
          - api.matrix.${DOMAIN}
      valkey:
        aliases:
          - matrix.${DOMAIN}
          - api.matrix.${DOMAIN}
      ldap:
        aliases:
          - matrix.${DOMAIN}
          - api.matrix.${DOMAIN}
      matrix-internal:
        aliases:
          - matrix.${DOMAIN}
          - api.matrix.${DOMAIN}
      authelia:
        aliases:
          - matrix.${DOMAIN}
          - api.matrix.${DOMAIN}
      internet:
    depends_on:
      postgres:
        condition: service_started
      synapse-init:
        condition: service_completed_successfully
      valkey:
        condition: service_started
      ldap:
        condition: service_started
      authelia:
        condition: service_started
    environment:
      DOMAIN: ${DOMAIN}
      SYNAPSE_SERVER_NAME: matrix.${DOMAIN}
      SYNAPSE_REPORT_STATS: yes
      SYNAPSE_ENABLE_REGISTRATION: ${MATRIX_ENABLE_REGISTRATION:-false}
      SYNAPSE_TRUSTED_PROXIES: 172.16.0.0/12
      SYNAPSE_LOG_LEVEL: WARNING
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: synapse
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: ${POSTGRES_SYNAPSE_PASSWORD}
      POSTGRES_SYNAPSE_PASSWORD: ${POSTGRES_SYNAPSE_PASSWORD}
      SYNAPSE_REGISTRATION_SECRET: ${SYNAPSE_REGISTRATION_SECRET}
      SYNAPSE_MACAROON_SECRET: ${SYNAPSE_MACAROON_SECRET}
      SYNAPSE_FORM_SECRET: ${SYNAPSE_FORM_SECRET}
      MATRIX_OAUTH_SECRET: ${MATRIX_OAUTH_SECRET}
      REDIS_HOST: redis-synapse
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      UID: 991
      GID: 991
    entrypoint: ["/data/entrypoint.sh"]
    volumes:
      - synapse_data:/data
      - ./configs/synapse/homeserver.yaml:/data/homeserver.yaml:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8008/health || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 120s
