services:
  integration-test-runner:
    build:
      context: .
      dockerfile: ./containers.src/test-runner/Dockerfile
    image: datamancy/test-runner:local-build
    container_name: integration-test-runner

    networks:
      - ai
      - postgres
      - mariadb
      - qdrant
      - ldap
      - valkey
      - monitoring
      - caddy
      - docker-proxy
      - authelia

    environment:
      AGENT_TOOL_SERVER_URL: "http://agent-tool-server:8081"
      SEARCH_SERVICE_URL: "http://search-service:8098"
      EMBEDDING_SERVICE_URL: "http://embedding-service:8080"

      LITELLM_URL: "http://litellm:4000"
      LITELLM_MASTER_KEY: "${LITELLM_MASTER_KEY}"
      CADDY_URL: "http://caddy:80"
      BOOKSTACK_URL: "http://bookstack:80"

      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "datamancy"
      POSTGRES_USER: "datamancer"
      POSTGRES_PASSWORD: "${POSTGRES_DATAMANCY_PASSWORD}"
      POSTGRES_ADMIN_PASSWORD: "${POSTGRES_ADMIN_PASSWORD}"
      POSTGRES_DATAMANCY_PASSWORD: "${POSTGRES_DATAMANCY_PASSWORD}"

      MARIADB_HOST: "mariadb"
      MARIADB_PORT: "3306"
      MARIADB_USER: "bookstack"
      MARIADB_PASSWORD: "${MARIADB_BOOKSTACK_PASSWORD}"
      MARIADB_ADMIN_PASSWORD: "${MARIADB_ADMIN_PASSWORD}"

      QDRANT_URL: "http://qdrant:6333"
      QDRANT_API_KEY: "${AGENT_QDRANT_API_KEY}"
      VALKEY_URL: "valkey:6379"

      AUTHELIA_URL: "https://auth.datamancy.net"
      LDAP_URL: "ldap://ldap:389"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_ADMIN_DN: "cn=admin,${LDAP_BASE_DN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"

      TEST_ENV: "container"
      TEST_USER_CONTEXT: "test-agent-user"
      STACK_ADMIN_USER: "${STACK_ADMIN_USER}"
      STACK_ADMIN_PASSWORD: "${STACK_ADMIN_PASSWORD}"

      BOOKSTACK_API_TOKEN_ID: "${BOOKSTACK_API_TOKEN_ID:-}"
      BOOKSTACK_API_TOKEN_SECRET: "${BOOKSTACK_API_TOKEN_SECRET:-}"

      REGISTRY_HOST: "registry:5000"
      HOST_IP: "${HOST_IP:-192.168.0.11}"

      NTFY_USERNAME: "${NTFY_USERNAME}"
      NTFY_PASSWORD: "${NTFY_PASSWORD}"

      DOCKER_HOST: "tcp://docker-proxy:2375"

    profiles:
      - testing

    restart: "no"


    user: "1000:1000"

    volumes:
      - ${HOME}/.ssh:/home/appuser/.ssh:ro

    tmpfs:
      - /tmp
