# Integration Testing Compose Overlay
# Provides a single test container with access to all networks
#
# Usage:
#   docker compose -f docker-compose.yml -f compose.templates/testing.yml \
#     --profile testing run --rm integration-test-runner
#
# Run specific suite:
#   docker compose --profile testing run --rm integration-test-runner foundation
#   docker compose --profile testing run --rm integration-test-runner docker
#   docker compose --profile testing run --rm integration-test-runner data-pipeline
#
# Interactive debugging:
#   docker compose --profile testing run --rm integration-test-runner bash

services:
  integration-test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test-runner
    image: datamancy/test-runner:latest
    container_name: integration-test-runner

    # ALL networks for integration testing (violates zero-trust, but essential for tests)
    networks:
      - ai
      - ai-gateway
      - postgres
      - mariadb
      - clickhouse
      - qdrant
      - ldap
      - valkey
      - backend
      - frontend
      - monitoring

    environment:
      # Service endpoints (Docker network hostnames)
      AGENT_TOOL_SERVER_URL: "http://agent-tool-server:8081"
      DATA_FETCHER_URL: "http://data-fetcher:8095"
      DATA_TRANSFORMER_URL: "http://data-transformer:8096"
      SEARCH_SERVICE_URL: "http://search-service:8098"
      CONTROL_PANEL_URL: "http://control-panel:8097"

      # Infrastructure services
      LITELLM_URL: "http://litellm:4000"
      CADDY_URL: "http://caddy:80"
      BOOKSTACK_URL: "http://bookstack:80"

      # Database connections
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "datamancy"
      POSTGRES_USER: "datamancer"

      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_USER: "default"

      MARIADB_HOST: "mariadb"
      MARIADB_PORT: "3306"

      # Vector/cache services
      QDRANT_URL: "http://qdrant:6333"
      VALKEY_URL: "valkey:6379"

      # Auth services
      LDAP_URL: "ldap://ldap:389"

      # Test configuration
      TEST_ENV: "container"
      TEST_USER_CONTEXT: "test-agent-user"
      STACK_ADMIN_PASSWORD: "${STACK_ADMIN_PASSWORD}"

      # BookStack API credentials (optional - for data pipeline tests)
      BOOKSTACK_API_TOKEN_ID: "${BOOKSTACK_API_TOKEN_ID:-}"
      BOOKSTACK_API_TOKEN_SECRET: "${BOOKSTACK_API_TOKEN_SECRET:-}"

    # Only run when explicitly requested
    profiles:
      - testing

    # Don't restart automatically
    restart: "no"

    # No persistent volumes needed (tests are ephemeral)
    tmpfs:
      - /tmp

networks:
  # All networks are defined in main docker-compose.yml
  # This overlay just connects to them
  ai:
    external: false
  ai-gateway:
    external: false
  postgres:
    external: false
  mariadb:
    external: false
  clickhouse:
    external: false
  qdrant:
    external: false
  ldap:
    external: false
  valkey:
    external: false
  backend:
    external: false
  frontend:
    external: false
  monitoring:
    external: false
