services:
  integration-test-runner:
    build:
      context: .
      dockerfile: ./containers.src/test-runner/Dockerfile
    image: datamancy/test-runner:local-build
    pull_policy: build
    container_name: integration-test-runner
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

    networks:
      - ai
      - postgres
      - mariadb
      - qdrant
      - ldap
      - valkey
      - monitoring
      - caddy
      - docker-proxy
      - authelia
      - trading

    environment:
      AGENT_TOOL_SERVER_URL: "http://agent-tool-server:8081"
      SEARCH_SERVICE_URL: "http://search-service:8098"
      EMBEDDING_SERVICE_URL: "http://embedding-service:8080"
      PIPELINE_URL: "http://pipeline:8090"

      LITELLM_URL: "http://litellm:4000"
      LITELLM_MASTER_KEY: "${LITELLM_MASTER_KEY}"
      CADDY_URL: "http://caddy"
      BASE_URL: "https://${DOMAIN}"
      BOOKSTACK_URL: "http://bookstack:80"

      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "datamancy"
      POSTGRES_USER: "${POSTGRES_TEST_RUNNER_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_TEST_RUNNER_PASSWORD}"
      POSTGRES_ADMIN_PASSWORD: "${POSTGRES_ADMIN_PASSWORD}"

      MARIADB_HOST: "mariadb"
      MARIADB_PORT: "3306"
      MARIADB_USER: "bookstack"
      MARIADB_PASSWORD: "${MARIADB_BOOKSTACK_PASSWORD}"
      MARIADB_ADMIN_PASSWORD: "${MARIADB_ADMIN_PASSWORD}"

      QDRANT_URL: "http://qdrant:6333"
      QDRANT_API_KEY: "${QDRANT_ADMIN_API_KEY}"
      VALKEY_URL: "valkey:6379"
      VALKEY_ADMIN_PASSWORD: "${VALKEY_ADMIN_PASSWORD}"

      AUTHELIA_URL: "https://auth.datamancy.net"
      LDAP_URL: "ldap://ldap:389"
      LDAP_BASE_DN: "${LDAP_BASE_DN}"
      LDAP_ADMIN_DN: "cn=admin,${LDAP_BASE_DN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"

      OIDC_CLIENT_ID: "test-runner"
      OIDC_CLIENT_SECRET: "${TEST_RUNNER_OAUTH_SECRET}"
      OIDC_REDIRECT_URI: "urn:ietf:wg:oauth:2.0:oob"

      TEST_ENV: "container"
      TEST_USER_CONTEXT: "test-agent-user"
      DOMAIN: "${DOMAIN}"
      STACK_ADMIN_USER: "${STACK_ADMIN_USER}"
      STACK_ADMIN_PASSWORD: "${STACK_ADMIN_PASSWORD}"

      BOOKSTACK_API_TOKEN_ID: "${BOOKSTACK_API_TOKEN_ID:-}"
      BOOKSTACK_API_TOKEN_SECRET: "${BOOKSTACK_API_TOKEN_SECRET:-}"

      REGISTRY_HOST: "registry:5000"
      HOST_IP: "${HOST_IP:-192.168.0.11}"

      NTFY_USERNAME: "${NTFY_USERNAME}"
      NTFY_PASSWORD: "${NTFY_PASSWORD}"

      DOCKER_HOST: "tcp://docker-proxy:2375"
      DISABLE_TLS_VALIDATION: "true"

    profiles:
      - testing

    restart: unless-stopped


    user: "1000:1000"

    volumes:
      - ${HOME}/.ssh:/home/testing_container_user/.ssh:ro

    tmpfs:
      - /tmp

networks:
  ai:
    external: true
    name: datamancy_ai
  postgres:
    external: true
    name: datamancy_postgres
  mariadb:
    external: true
    name: datamancy_mariadb
  qdrant:
    external: true
    name: datamancy_qdrant
  ldap:
    external: true
    name: datamancy_ldap
  valkey:
    external: true
    name: datamancy_valkey
  monitoring:
    external: true
    name: datamancy_monitoring
  caddy:
    external: true
    name: datamancy_caddy
  docker-proxy:
    external: true
    name: datamancy_docker-proxy
  authelia:
    external: true
    name: datamancy_authelia
  trading:
    external: true
    name: datamancy_trading
