services:
  valkey:
    image: valkey/valkey:8.1.5
    container_name: valkey
    restart: unless-stopped
    networks:
      - valkey
    environment:
      VALKEY_PASSWORD: ${VALKEY_ADMIN_PASSWORD}
    volumes:
      - redis_data:/data
    command: valkey-server --appendonly yes --dir /data --databases 16 --requirepass ${VALKEY_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "sh", "-c", "valkey-cli -a $$VALKEY_PASSWORD ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
