services:
  valkey:
    image: valkey/valkey:8.1.5
    container_name: valkey
    restart: unless-stopped
    networks:
      - valkey
    environment:
      VALKEY_PASSWORD: ${VALKEY_ADMIN_PASSWORD}
    volumes:
      - redis_data:/data
      - valkey_acl:/etc/valkey
    command: valkey-server --appendonly yes --dir /data --databases 16 --aclfile /etc/valkey/users.acl
    healthcheck:
      test:
        - CMD-SHELL
        - |
          valkey-cli --user default -a "$$VALKEY_PASSWORD" ping >/dev/null && \
          valkey-cli --user default -a "$$VALKEY_PASSWORD" SET healthcheck:test "$$RANDOM" EX 5 >/dev/null && \
          valkey-cli --user default -a "$$VALKEY_PASSWORD" GET healthcheck:test >/dev/null && \
          valkey-cli --user default -a "$$VALKEY_PASSWORD" INFO replication | grep -q role:master
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  valkey-init:
    image: valkey/valkey:8.1.5
    container_name: valkey-init
    restart: no
    networks:
      - valkey
    depends_on:
      valkey:
        condition: service_started
    environment:
      VALKEY_ADMIN_PASSWORD: ${VALKEY_ADMIN_PASSWORD}
      VALKEY_AUTHELIA_PASSWORD: ${VALKEY_AUTHELIA_PASSWORD}
      VALKEY_SEAFILE_PASSWORD: ${VALKEY_SEAFILE_PASSWORD}
      VALKEY_MASTODON_PASSWORD: ${VALKEY_MASTODON_PASSWORD}
    volumes:
      - ./configs/valkey/init-acl.sh:/init-acl.sh:ro
      - valkey_acl:/etc/valkey
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        echo "===== valkey-init starting ====="

        # Ensure /etc/valkey directory exists and has correct permissions
        mkdir -p /etc/valkey
        chmod 777 /etc/valkey

        # Create initial ACL file if it doesn't exist
        if [ ! -f /etc/valkey/users.acl ]; then
          echo "Creating initial ACL file with default user..."
          echo "user default on >${VALKEY_ADMIN_PASSWORD} ~* &* +@all" > /etc/valkey/users.acl
          chmod 666 /etc/valkey/users.acl
        fi

        sh /init-acl.sh
        touch /tmp/init_complete
        echo "===== Valkey ACL initialization complete ====="
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/init_complete"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  valkey_acl:
