services:
  vaultwarden:
    image: vaultwarden/server:testing
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - vaultwarden.${DOMAIN}
          - app.vaultwarden.${DOMAIN}
      postgres:
        aliases:
          - vaultwarden.${DOMAIN}
          - app.vaultwarden.${DOMAIN}
      mailserver:
        aliases:
          - vaultwarden.${DOMAIN}
          - app.vaultwarden.${DOMAIN}
      authelia:
        aliases:
          - vaultwarden.${DOMAIN}
          - app.vaultwarden.${DOMAIN}
    depends_on:
      postgres:
        condition: service_healthy
      mailserver:
        condition: service_healthy
      authelia:
        condition: service_healthy
    environment:
      DOMAIN: https://app.vaultwarden.${DOMAIN}
      DATABASE_URL: postgresql://vaultwarden:${VAULTWARDEN_DB_PASSWORD}@postgres:5432/vaultwarden
      SIGNUPS_ALLOWED: false
      SIGNUPS_VERIFY: true
      SIGNUPS_DOMAINS_WHITELIST: ${MAIL_DOMAIN}
      INVITATIONS_ALLOWED: false
      SHOW_PASSWORD_HINT: false
      SSO_ENABLED: true
      SSO_ONLY: true
      SSO_AUTHORITY: https://auth.${DOMAIN}
      SSO_CLIENT_ID: vaultwarden
      SSO_CLIENT_SECRET: ${VAULTWARDEN_OAUTH_SECRET}
      SSO_SCOPES: openid email profile
      SSO_CALLBACK_PATH: /identity/connect/oidc-signin
      SSO_SIGNUPS_MATCH_EMAIL: true
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      SMTP_HOST: mailserver
      SMTP_FROM: vaultwarden@${MAIL_DOMAIN}
      SMTP_PORT: 587
      SMTP_SECURITY: starttls
      SMTP_USERNAME: vaultwarden@${MAIL_DOMAIN}
      SMTP_PASSWORD: ${VAULTWARDEN_SMTP_PASSWORD}
    volumes:
      - vaultwarden_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/alive || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
