services:
  ldap-account-manager:
    image: ghcr.io/ldapaccountmanager/lam:9.4
    container_name: ldap-account-manager
    restart: unless-stopped
    networks:
      caddy:
      ldap:
        aliases:
          - lam.${DOMAIN}
    depends_on:
      caddy:
        condition: service_started
      ldap:
        condition: service_started
    environment:
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_USER: cn=admin,${LDAP_BASE_DN}
      LAM_SKIP_PRECONFIGURE: "true"
      LAM_LANG: en_US
    volumes:
      - ./configs/lam/config.cfg:/etc/ldap-account-manager/config.cfg:ro
      - ./configs/lam/lam.conf:/var/lib/ldap-account-manager/config/lam.conf:ro
      - ./configs/lam/login.php:/usr/share/ldap-account-manager/templates/login.php:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/lam/templates/login.php"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
