http:
  address: 0.0.0.0:4195
  enabled: true
  root_path: /benthos
  debug_endpoints: true

cache_resources:
  - label: dedupe_mem
    memory: {}

input:
  broker:
    inputs:
      - label: ingest_text
        http_server:
          address: 0.0.0.0:4196
          path: /ingest/text
          allowed_verbs: [ POST ]
        processors:
          # Check with RAG gateway if ingestion should proceed
          - branch:
              request_map: 'root = {}'
              processors:
                - try:
                  - http:
                      url: ${RAG_GATEWAY_URL:http://rag-gateway:8094}/api/ingestion/should-accept-data
                      verb: GET
                      rate_limit: ""
                      timeout: 5s
                      retries: 2
              result_map: |
                root.should_accept = this.shouldAccept.or(true)
          # Drop message if ingestion is paused
          - bloblang: 'root = if !this.should_accept { deleted() }'
          - mapping: |
              root = this
              root.route = "text"
              root.collection = this.collection.or(env("TARGET_COLLECTION")).or("rss_aggregation")
              root.id = this.id.or(uuid_v4())
              root.text = this.text.or("")
              root.payload = this.payload.or({})
              # also store raw text in payload for retrieval
              root.payload.text = root.text
              root.payload.content = root.text
          - bloblang: 'root = if this.text == "" { deleted() }'
          - dedupe:
              cache: dedupe_mem
              key: "${! this.id }"
          - branch:
              request_map: |
                root = { "inputs": this.text }
              processors:
                - http:
                    url: http://embedding-service:8080/embed
                    verb: POST
                    headers:
                      Content-Type: application/json
              result_map: 'root.vector = this.0'

      - label: ingest_series
        http_server:
          address: 0.0.0.0:4197
          path: /ingest/series
          allowed_verbs: [ POST ]
        processors:
          - mapping: |
              root = this
              root.route = "series"
              root.provider = this.provider.or("FRED")
              root.dataset = this.dataset.or("fred")
              root.series_id = this.series_id.or("")
              root.ts = this.ts.or(now())
              root.value = this.value.or(0.0)
              root.revision = this.revision.or(0)
          - bloblang: 'root = if this.series_id == "" { deleted() }'

output:
  switch:
    cases:
      - check: this.route == "text"
        output:
          http_client:
            url: ${QDRANT_URL:http://qdrant:6333}/collections/${! this.collection }/points?wait=true
            verb: PUT
            headers:
              Content-Type: application/json
              api-key: ${QDRANT_API_KEY:}
            batch_as_multipart: false
          processors:
            - mapping: |
                root = {
                  "points": [ { "id": this.id, "vector": this.vector, "payload": this.payload } ]
                }
      - check: this.route == "series"
        output:
          sql_insert:
            driver: clickhouse
            dsn: ${CLICKHOUSE_DSN}
            table: series_values
            columns: ["provider", "dataset", "series_id", "ts", "value", "revision"]
            args_mapping: |
              root = [ this.provider, this.dataset, this.series_id, this.ts, this.value, this.revision ]

metrics:
  prometheus:
    push_url: ""
    push_interval: 1m

logger:
  level: INFO
  format: json
  add_timestamp: true
