#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DIST_DIR="$PROJECT_ROOT/dist"
FORGEJO_URL="${FORGEJO_URL:-https://forgejo.datamancy.net}"
FORGEJO_USER="${FORGEJO_DEPLOY_USER:-datamancy-bot}"
FORGEJO_TOKEN="${FORGEJO_DEPLOY_TOKEN:-}"
REPO_ORG="datamancy"
REPO_NAME="deployment-config"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'
log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}
log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}
log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}
log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}
if [ ! -d "$DIST_DIR" ]; then
    log_error "dist/ directory not found at $DIST_DIR"
    log_error "Run build-datamancy-v2.main.kts first"
    exit 1
fi
if [ -z "$FORGEJO_TOKEN" ]; then
    log_warning "FORGEJO_DEPLOY_TOKEN not set - skipping Forgejo bundling"
    log_info "To enable, set FORGEJO_DEPLOY_TOKEN environment variable"
    log_info "Create token at: $FORGEJO_URL/user/settings/applications"
    exit 0
fi
log_info "Bundling deployment artifacts to Forgejo..."
log_info "Repository: $FORGEJO_URL/$REPO_ORG/$REPO_NAME"
cd "$DIST_DIR"
if [ ! -d .git ]; then
    log_info "Initializing Git repository in dist/"
    git init
    git config user.name "Datamancy Build Bot"
    git config user.email "build@datamancy.net"
fi
log_info "Creating .gitignore..."
cat > .gitignore <<'EOF'
.env
volumes/
*.log
*.pid
*.jar.tmp
*.swp
*~
.idea/
*.iml
.vscode/
.DS_Store
Thumbs.db
EOF
log_info "Creating .env.template with secret placeholders..."
if [ -f .env ]; then
    sed -E 's/^([A-Z_]+)=(.+)$/\1=CHANGEME_\1/g' .env > .env.template
    log_success ".env.template created with ${YELLOW}${GREEN} placeholders"
else
    log_warning ".env not found - skipping .env.template generation"
fi
log_info "Creating README.md..."
cat > README.md <<'EOF'
This repository contains the complete deployment configuration for the Datamancy stack.
- `docker-compose.yml` - Complete service definitions
- `.env.template` - Environment variable template (secrets placeholder)
- `configs/` - Service configuration files
- `containers.src/` - Custom container build contexts
- `.build-info` - Build metadata (commit hash, timestamp)
```bash
git clone https://forgejo.datamancy.net/datamancy/deployment-config.git
cd deployment-config
cp .env.template .env
docker compose up -d
docker compose logs -f
docker compose --profile testing run --rm integration-test-runner all
```
```bash
git clone https://forgejo.datamancy.net/datamancy/deployment-config.git
cd deployment-config
export DOCKER_HOST=ssh://labware
docker compose up -d
docker compose run --rm integration-test-runner all
docker compose down -v
```
In case of complete system failure:
1. Clone this repository on new hardware
2. Restore `.env` from secure backup
3. Run `docker compose up -d`
4. Restore volume data from backups (optional, if not using external storage)
See `.build-info` for:
- Build timestamp
- Source commit hash
- Builder information
- **Never commit `.env` file** - it contains real secrets
- Use `.env.template` as reference for required variables
- Store real `.env` in secure vault (1Password, Vault, etc.)
- Rotate secrets regularly
---
🤖 Generated by Datamancy Build System
EOF
log_info "Staging files for commit..."
git add -A
if git diff --cached --quiet; then
    log_info "No changes to commit - repository is up to date"
else
    BUILD_INFO=""
    if [ -f .build-info ]; then
        BUILD_INFO=$(cat .build-info)
    fi
    COMMIT_MSG="Deploy: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
$BUILD_INFO
Files updated:
$(git diff --cached --name-only | head -20)
Generated by build-datamancy-v2.main.kts"
    log_info "Creating commit..."
    git commit -m "$COMMIT_MSG"
    log_success "Commit created"
fi
REMOTE_URL="https://${FORGEJO_USER}:${FORGEJO_TOKEN}@${FORGEJO_URL#https://}/${REPO_ORG}/${REPO_NAME}.git"
if git remote | grep -q origin; then
    git remote set-url origin "$REMOTE_URL"
else
    git remote add origin "$REMOTE_URL"
fi
log_info "Pushing to Forgejo..."
if git push -u origin main 2>&1; then
    log_success "Successfully pushed to $FORGEJO_URL/$REPO_ORG/$REPO_NAME"
    log_success "View at: $FORGEJO_URL/$REPO_ORG/$REPO_NAME"
else
    EXIT_CODE=$?
    log_error "Failed to push to Forgejo (exit code: $EXIT_CODE)"
    log_warning "Repository may not exist - create it at:"
    log_warning "  $FORGEJO_URL/repo/create"
    log_warning "  Organization: $REPO_ORG"
    log_warning "  Name: $REPO_NAME"
    exit $EXIT_CODE
fi
log_success "Deployment artifacts bundled successfully!"
log_info "Next steps:"
log_info "  1. Clone: git clone $FORGEJO_URL/$REPO_ORG/$REPO_NAME.git"
log_info "  2. Configure: cp .env.template .env && vim .env"
log_info "  3. Deploy: docker compose up -d"
