wiki:
  dumpsUrl: "https://dumps.wikimedia.org/enwiki/latest/"
  apiUrl: "https://en.wikipedia.org/w/api.php"
  wikidataUrl: "https://www.wikidata.org/w/api.php"

rss:
  feeds:
    - url: "https://lobste.rs/rss"
      category: "tech"

    - url: "https://rss.arxiv.org/rss/cs"
      category: "research"
    - url: "https://rss.arxiv.org/rss/cs.AI"
      category: "research_ai"

    - url: "https://www.abc.net.au/news/feed/51120/rss.xml"
      category: "news_au"
    - url: "https://feeds.bbci.co.uk/news/world/rss.xml"
      category: "news_world"

marketData:
  symbols:
    - "BTC"
    - "ETH"
    - "SOL"
    - "AAPL"
    - "GOOGL"
    - "MSFT"

  cryptoSources:
    - "coingecko"

  stockSources:
    - "yahoo"

weather:
  locations:
    - "Sydney"
    - "Melbourne"
    - "Brisbane"
    - "Perth"
    - "Adelaide"
  apiKey: "${OPENWEATHER_API_KEY}"

economic:
  sources:
    - "imf"
    - "worldbank"
    - "oecd"
    - "fred"

  fredApiKey: "${FRED_API_KEY}"

search:
  apiKey: "${SERP_API_KEY}"
  queries:
    - "latest AI research"
    - "machine learning papers"
    - "Kotlin programming"

legal:
  ausLegislationUrl: "https://www.legislation.gov.au/"
  stateUrls:
    nsw: "https://legislation.nsw.gov.au/"
    vic: "https://www.legislation.vic.gov.au/"
    qld: "https://www.legislation.qld.gov.au/"
    wa: "https://www.legislation.wa.gov.au/"
    sa: "https://www.legislation.sa.gov.au/"
    tas: "https://www.legislation.tas.gov.au/"
    act: "https://legislation.act.gov.au/"
    nt: "https://legislation.nt.gov.au/"

torrents:
  torrentsCsvUrl: "https://torrents-csv.com/service/search"
  qbittorrentUrl: "http://qbittorrent:8080"
  autoDownload: false

docs:
  sources:
    - name: "linux_kernel"
      url: "https://www.kernel.org/doc/html/latest/"
      category: "linux"

    - name: "debian_docs"
      url: "https://www.debian.org/doc/"
      category: "debian"

    - name: "kotlin_docs"
      url: "https://kotlinlang.org/docs/"
      category: "programming"
