target_collection: macro_series_meta
required_env:
  - FRED_API_KEY
  - IMF_API_KEY
  - OECD_APP_KEY
notes:
  - Pull series metadata/descriptions from providers
  - Build text contexts, embed (via LiteLLM), upsert to Qdrant
