services:
  test-runner-llm:
    build:
      context: .
      dockerfile: ./tests.containers/test-runner/Dockerfile
    image: datamancy/test-runner:local-build
    pull_policy: build
    container_name: test-runner-llm
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

    tmpfs:
      - /tmp
    networks:
      - default
      - internet
      - postgres
      - mariadb
      - qdrant
      - valkey
      - ldap
      - authelia
      - mailserver
      - memcached
      - docker-proxy
      - caddy
      - ai
      - litellm
      - monitoring
      - mastodon-internal
      - matrix-internal
      - trading
