services:
  test-runner-agent-orchestration:
    build:
      context: .
      dockerfile: ./tests.containers/test-runner/Dockerfile
    image: datamancy/test-runner:local-build
    pull_policy: build
    container_name: test-runner-agent-orchestration
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

    tmpfs:
      - /tmp
