# Communication and collaboration services
# Synapse (Matrix), Element, Mastodon, Roundcube, Radicale

services:
  synapse:
    build:
      dockerfile: ./src/synapse/Dockerfile
      context: .
    container_name: synapse
    restart: unless-stopped
    user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
    depends_on:
      postgres:
        condition: service_started
      valkey:
        condition: service_started
      ldap:
        condition: service_started
    environment:
      - SYNAPSE_SERVER_NAME=matrix.${DOMAIN}
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_ENABLE_REGISTRATION=${MATRIX_ENABLE_REGISTRATION:-false}
      - SYNAPSE_TRUSTED_PROXIES=172.18.0.0/16,172.21.0.0/24
      - SYNAPSE_LOG_LEVEL=WARNING
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${SYNAPSE_DB_PASSWORD}
      - REDIS_HOST=redis-synapse
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    volumes:
      - synapse_data:/data
      - ${HOME}/.datamancy/configs/applications/synapse/homeserver.yaml:/data/homeserver.yaml:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  element:
    image: vectorim/element-web:v1.11.88
    container_name: element
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - element_data:/app/config
      - ${HOME}/.datamancy/configs/applications/element/config.json:/app/config.json:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mastodon-web:
    image: ghcr.io/mastodon/mastodon:v4.3.3
    container_name: mastodon-web
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - postgres
      - valkey
    env_file:
      - ${HOME}/.datamancy/configs/applications/mastodon/mastodon.env
    volumes:
      - mastodon_data:/mastodon/public/system
      - ${HOME}/.datamancy/configs/applications/mastodon/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s

  mastodon-streaming:
    image: ghcr.io/mastodon/mastodon-streaming:v4.3.3
    container_name: mastodon-streaming
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - postgres
      - valkey
    env_file:
      - ${HOME}/.datamancy/configs/applications/mastodon/mastodon.env
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mastodon-sidekiq:
    image: ghcr.io/mastodon/mastodon:v4.3.3
    container_name: mastodon-sidekiq
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - postgres
      - valkey
    env_file:
      - ${HOME}/.datamancy/configs/applications/mastodon/mastodon.env
    command: bundle exec sidekiq
    volumes:
      - mastodon_data:/mastodon/public/system
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    healthcheck:
      test: ["CMD-SHELL", "bundle exec rails runner 'exit(Sidekiq::ProcessSet.new.size > 0 ? 0 : 1)' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=postgres
      - ROUNDCUBEMAIL_DB_PORT=5432
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=${STACK_ADMIN_PASSWORD}
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=50M
    volumes:
      - roundcube_data:/var/www/html
      - ${HOME}/.datamancy/configs/applications/roundcube/config.inc.php:/var/www/html/config/config.inc.php:ro
    networks:
      - backend
    depends_on:
      - postgres
      - mailserver
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - radicale_data:/data
      - ${HOME}/.datamancy/configs/applications/radicale/config:/config/config:ro
      - ${HOME}/.datamancy/configs/applications/radicale/users:/data/users
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5232/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
