# File storage and document collaboration
# Seafile, OnlyOffice

services:
  seafile:
    image: seafileltd/seafile-mc:13.0.12
    container_name: seafile
    restart: unless-stopped
    depends_on:
      - mariadb
      - memcached
    environment:
      - TZ=UTC
      - DB_HOST=mysql
      - DB_ROOT_PASSWD=${MARIADB_ROOT_PASSWORD}
      - SEAFILE_MYSQL_DB_HOST=mysql
      - SEAFILE_MYSQL_DB_PORT=3306
      - SEAFILE_MYSQL_DB_USER=seafile
      - SEAFILE_MYSQL_DB_PASSWORD=${MARIADB_SEAFILE_PASSWORD}
      - INIT_SEAFILE_MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=seafile.${DOMAIN}
      - SEAFILE_ADMIN_EMAIL=${STACK_ADMIN_EMAIL}
      - SEAFILE_ADMIN_PASSWORD=${STACK_ADMIN_PASSWORD}
      - JWT_PRIVATE_KEY=${SEAFILE_JWT_KEY}
      - TIME_ZONE=UTC
    volumes:
      - seafile_data:/shared
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/ | grep -E '^(200|302)$'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 180s

  onlyoffice:
    image: onlyoffice/documentserver:8.2.2
    container_name: onlyoffice
    restart: unless-stopped
    depends_on:
      - seafile
    environment:
      - TZ=UTC
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - JWT_HEADER=Authorization
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/healthcheck"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 2m
