#!/usr/bin/env bash
# bootstrap-stack.sh — Manage Datamancy bootstrap and switch to full stack
#
# Keeps the ISO generic: you run this script after cloning the repo on a host
# where Docker is installed (see scripts/setup-host.sh).
#
# Commands:
#   init           Ensure repo env for bootstrap (.env.bootstrap)
#   up-bootstrap   Start docker-compose.bootstrap.yml
#   down-bootstrap Stop bootstrap stack
#   switch-to-full Stop bootstrap and start docker-compose.yml (requires .env)
#   status         Show docker ps summary
#
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

compose_bootstrap() {
  docker compose -f "$repo_root/docker-compose.bootstrap.yml" --env-file "$repo_root/.env.bootstrap" "$@"
}

compose_full() {
  docker compose -f "$repo_root/docker-compose.yml" --env-file "$repo_root/.env" "$@"
}

random_hex() {
  # 16 bytes -> 32 hex chars
  openssl rand -hex 16
}

ensure_env_bootstrap() {
  if [[ ! -f "$repo_root/.env.bootstrap" ]]; then
    local key
    key=$(random_hex)
    cat > "$repo_root/.env.bootstrap" <<EOF
# Autogenerated minimal bootstrap env
# Do NOT share this file; it may contain secrets.
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY:-$key}
# Optional: if you have a HuggingFace token, uncomment and set it
# HUGGINGFACEHUB_API_TOKEN=
EOF
    chmod 0640 "$repo_root/.env.bootstrap" || true
  fi
}

usage() {
  cat <<USAGE
Usage: $(basename "$0") <command>
Commands:
  init            Create .env.bootstrap if missing
  up-bootstrap    Start bootstrap stack (Open WebUI @ http://localhost:8080)
  down-bootstrap  Stop bootstrap stack and remove containers (volumes preserved)
  switch-to-full  Stop bootstrap and start full stack (requires .env)
  status          Show container status summary
USAGE
}

case "${1:-}" in
  init)
    ensure_env_bootstrap
    ;;
  up-bootstrap)
    ensure_env_bootstrap
    compose_bootstrap up -d --pull=missing
    ;;
  down-bootstrap)
    compose_bootstrap down
    ;;
  switch-to-full)
    compose_bootstrap down || true
    if [[ ! -f "$repo_root/.env" ]]; then
      echo "ERROR: $repo_root/.env not found. Create it first, then re-run." >&2
      exit 1
    fi
    compose_full up -d --pull=missing
    ;;
  status)
    docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}'
    ;;
  *)
    usage
    exit 1
    ;;
esac
