FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    wget \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir selenium

WORKDIR /test

COPY test-oidc-selenium.py /test/

CMD ["python", "test-oidc-selenium.py"]
