package org.datamancy.pipeline.sources.standardized

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import org.datamancy.pipeline.core.Chunkable
import org.datamancy.pipeline.core.StandardizedSource
import org.datamancy.pipeline.scheduling.BackfillStrategy
import org.datamancy.pipeline.scheduling.ResyncStrategy
import org.datamancy.pipeline.scheduling.RunMetadata
import org.datamancy.pipeline.sinks.BookStackDocument
import org.datamancy.pipeline.sources.WikipediaArticle
import org.datamancy.pipeline.sources.WikipediaSource

/**
 * STANDARDIZED Wikipedia Source
 *
 * - Daily resync at 1am
 * - Full dump on initial pull
 * - Re-stream dump on resync (Wikipedia doesn't have good incremental API)
 * - Chunking REQUIRED (articles are long)
 */
class WikipediaStandardizedSource(
    private val dumpUrl: String,
    private val maxArticles: Int = Int.MAX_VALUE
) : StandardizedSource<WikipediaChunkableArticle> {

    override val name = "wikipedia"

    override fun resyncStrategy(): ResyncStrategy {
        // Large source - check daily at 1am
        return ResyncStrategy.DailyAt(hour = 1, minute = 0)
    }

    override fun backfillStrategy(): BackfillStrategy {
        return BackfillStrategy.WikipediaDump(
            dumpUrl = dumpUrl,
            maxArticles = maxArticles
        )
    }

    override fun needsChunking(): Boolean {
        // Wikipedia articles are LONG - chunking is REQUIRED
        return true
    }

    override suspend fun fetchForRun(metadata: RunMetadata): Flow<WikipediaChunkableArticle> {
        // Wikipedia doesn't have a good incremental API
        // Always stream the full dump (but Qdrant dedup will skip unchanged articles)
        return WikipediaSource(
            dumpPath = dumpUrl,
            maxArticles = maxArticles,
            maxChunkSize = 10000,  // Large size, we'll chunk properly with Chunker
            chunkOverlap = 0  // No overlap here, Chunker handles it
        ).fetch()
            .map { article -> WikipediaChunkableArticle(article) }
    }
}

/**
 * Wrapper to make WikipediaArticle implement Chunkable
 */
data class WikipediaChunkableArticle(val article: WikipediaArticle) : Chunkable {
    override fun toText(): String = article.text

    override fun getId(): String = article.originalArticleId

    override fun getMetadata(): Map<String, String> = mapOf(
        "title" to article.title,
        "wikipedia_id" to article.id,
        "source" to "wikipedia"
    )

    fun toBookStackDocument(): BookStackDocument {
        // Extract first paragraph as summary
        val summary = article.text.lines()
            .filter { it.isNotBlank() }
            .firstOrNull() ?: article.text.take(500)

        return BookStackDocument(
            bookName = "Wikipedia",
            bookDescription = "Articles from Wikipedia, the free encyclopedia",
            chapterName = null,  // No chapter grouping - flat structure
            pageTitle = article.title,
            pageContent = """
                <h1>${article.title}</h1>
                <div style="margin-bottom: 20px; padding: 10px; background-color: #f8f9fa; border-left: 4px solid #339966;">
                    <p><strong>Wikipedia ID:</strong> ${article.id}</p>
                    <p><strong>Source:</strong> <a href="https://en.wikipedia.org/wiki/${article.title.replace(" ", "_")}" target="_blank">View on Wikipedia</a></p>
                </div>
                <div style="margin-top: 20px;">
                    <h2>Summary</h2>
                    <p><em>${summary}</em></p>
                </div>
                <div style="margin-top: 20px;">
                    <h2>Content</h2>
                    <div style="white-space: pre-wrap; word-wrap: break-word; font-family: Georgia, serif; line-height: 1.6;">
                        ${article.text.split("\n\n").joinToString("\n") { para ->
                            if (para.isNotBlank()) "<p>${para.replace("\n", " ")}</p>" else ""
                        }}
                    </div>
                </div>
                <hr>
                <p style="font-size: 0.9em; color: #666;">
                    <em>This page was automatically generated by Datamancy Pipeline from Wikipedia.
                    Content is available under <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank">CC BY-SA 3.0</a></em>
                </p>
            """.trimIndent(),
            tags = mapOf(
                "source" to "wikipedia",
                "wikipedia_id" to article.id,
                "title" to article.title
            )
        )
    }
}
